version: "2.6"

services:
  app:
    build: .
    container_name: spring-app
    ports:
      - "8081:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/bank_rest_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1
    depends_on:
      - db
  db:
    image: postgres:16
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: bank_rest_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  spring-tests:
    image: maven:3.9.9-eclipse-temurin-17
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/bank_rest_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1
    command: mvn -B test
volumes:
  db_data:


